import { Nav } from './components/nav'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <div className="overflow-hidden w-full h-full relative">
          <div className="flex h-full flex-1 flex-col md:pl-[260px]">
            {children}
          </div>
          <Nav />
        </div>
      </body>
    </html>
  )
}
